### ISSUE TITLE
presets.xml is missing

### ISSUE THREAD

**Issue by app-akrobaten** [trsonic/nvsonic-head-tracker#10]
the presets.xml is missing... I have located in the same folder like the program itself.

MacOS 11.2.1.
OSC Bridge version 3.0

**Comment by quentinvp** [comment]
Hi, MacOS 11.2.3, presets.xml still missing with the file in the same folder... any issue?

**Comment by trsonic** [comment]
Hi,

I've pushed a fix. I've also updated the macOS binary in the latest release. Should work now.

Cheers!
