### ISSUE TITLE
yaw pitch roll

### ISSUE THREAD

**Issue by quentinvp** [trsonic/nvsonic-head-tracker#11]
Thanks for the update in the Bridge!

I have another problem, config: arduino leonardo, MPU 9250.
I compiled the device, but in the bridge, and in my OSC receiver, pitch and roll seems to be ok (even if the move is too fast angle data go too far then come back in the right position) but the Yaw doesn't work... I have some data in Yaw (Z) parameter, but dont correspond on my head rotation.

Any idea? Thanks again!

**Comment by trsonic** [comment]
This sounds like a broken MPU9250 board. Unfortunately, some just don't work correctly.

Anyway, you might want to post a video of this behavior so we can try to verify this.

**Comment by quentinvp** [comment]
Arf... Bad news... I just try another 9250 board, and only the pitch is fine...
I will try to find other boards!
Thanks for the answer!

**Comment by quentinvp** [comment]
Hey!
Just receive new boards, and it works, thanks for your help !!
