### ISSUE TITLE
presets

### ISSUE THREAD

**Issue by gzalles** [trsonic/nvsonic-head-tracker#15]
xml file not found Big Sur. I tried moving the xml file inside app in various folders and also adding full disk permissions to app. none of the above resolved the issue.

ideas?

**Comment by trsonic** [comment]
closing this one, feel free to reopen if the presets are not showing up in the latest build

**Comment by gzalles** [comment]
thank you tomasz. i might be using this for an experiment in the near future. i will give you a shout out.

**Comment by gzalles** [comment]
<3

**Comment by gzalles** [comment]
mmm, took me a long time to come back around to this but no, it seems to not be fixed. i simply input the values manually from the XML file and that works V3.1 does not seem populate the JUCE app with the presets... :(
