### ISSUE TITLE
Arduino Nano 33 BLE instead of Arduino Pro Micro?

### ISSUE THREAD

**Issue by halbius** [trsonic/nvsonic-head-tracker#16]
Hi,

I wanted to build a new nvsonic-head-tracker and found out there is a new Arduino Nano 33 BLE with integrated IMU.
My question: Is it possible to use this one instead of Arduinio Pro Micro?
I am not that familiar with coding, so I cannot take a look at the code and change it, if needed.

Thanks a lot for your any help!

**Comment by trsonic** [comment]
Hi,

I'm sorry but the Arduino Nano 33 BLE uses LSM9DS1 IMU. This project will work only with Invensense MPU-XXXX IMUs.

Best,
T.
