### ISSUE TITLE
Orientation is inverted in Reaper

### ISSUE THREAD

**Issue by meta-meta** [trsonic/nvsonic-head-tracker#2]
![image](https://user-images.githubusercontent.com/2626819/59132367-a15f5a00-893a-11e9-97ab-caf049a392d6.png)

-180..180 is mapped to 1..0 causing inverted mappings in FB360. Is this by design?

**Comment by meta-meta** [comment]
Ah, I see https://github.com/trsonic/nvsonic-head-tracker/blob/master/head-tracker-osc-bridge/Source/Bridge.cpp#L114

I think a toggle to invert the mapping would be useful. To my knowledge, there's no way to remap in Reaper.

**Comment by halbius** [comment]
Hi,

is there a way to use a Arduino Nano v3.0 instead of the Pro Micro?

**Comment by trsonic** [comment]
Yep, I agree. I have to make it customizable. Different plugins use different polar coordinate systems. Current release was tested with ambiX rotator exclusively [http://www.matthiaskronlachner.com/?p=2015)]. I'm glad you sorted it out.
