### ISSUE TITLE
Arduino Nano instead of Pro Micro

### ISSUE THREAD

**Issue by halbius** [trsonic/nvsonic-head-tracker#3]
Hi,

is there a way to use an Arduino Nano v.30 instead of ProMicro?

If got some lying around and it would be nice to use them instead of buying new ones.

Thanks a lot!

**Comment by trsonic** [comment]
I haven't try it before, but I believe it is possible to make it work. The main difference between these two boards are their microcontrollers and how they handle the USB connectivity. There should be no difference from the user perspective.
