### ISSUE TITLE
Configure port and OSC addresses

### ISSUE THREAD

**Issue by meta-meta** [trsonic/nvsonic-head-tracker#4]
I would like to have 2 independently headphones for mixing 360 with a partner. I can connect 2 trackers to 1 PC, load 2 instances of the OSC Bridge and see both trackers working simultaneously. There is no way to differentiate between the two instances in Reaper. 

Being able to set an OSC port for each instance might allow me to create another OSC device in Reaper and I think in general is a desirable feature.

Another approach which is more flexible and perhaps more reliable (I'm not 100% sure that separate OSC devices in Reaper won't clash when using the same OSC address) would be to customize the OSC addresses for yaw pitch and roll. 

Bonus points: This almost opens up the opportunity to bypass Reaper's OSC learn and use SPARTA AmbiBIN, though it looks like they also expect a 3 member array at `/ypr`: http://research.spa.aalto.fi/projects/sparta_vsts/plugins.html So being able to choose between separate messages for each coordinate or an array at 1 address would be another nice feature.

**Comment by sonobianca** [comment]
I would also love to be able to do that.  I'm not C++ savvy, but from what I can see, the OSC Bridge seem to be able to get its OSC grammar from outside the code, but it's not clear to me how the file should be named, where it should be located and how it'S structured...  lack of C++ and Juce knowledge.

I'm trying to revive this thread!

**Comment by trsonic** [comment]
I've started implementing a customization of the OSC output format. I still need to implement the preset management. Although, custom output can be set using the GUI and will be saved between sessions. Just compile the latest code. No binaries yet.

It allows for using a quaternion array output, single ypr's or 3 member ypr array. The order of the arrays can be configured. Min and max values can be set as well.

![new osc configuration widnow](https://user-images.githubusercontent.com/28367809/92697878-11ce0580-f34c-11ea-8809-7fc0cc3e55f7.png)


Cheers,
T.
