### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by jaredsking123** [trsonic/nvsonic-head-tracker#7]
Hello,

I'm getting an error when I got to verify the sketch in Arduino - any thoughts?

`sketch/inv_mpu.cpp:50:0: warning: "min" redefined
 #define min(a,b) ((a<b)?a:b)
 
In file included from sketch/I2Cdev.h:77:0,
                 from sketch/inv_mpu.h:24,
                 from sketch/inv_mpu.cpp:25:
/private/var/folders/yt/fhd66_9n1qq7dtkgr5vr8g880000gn/T/AppTranslocation/ED2C9ABF-55B7-4361-9AA9-AE220C41465E/d/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h:92:0: note: this is the location of the previous definition
 #define min(a,b) ((a)<(b)?(a):(b))
 
Sketch uses 17478 bytes (60%) of program storage space. Maximum is 28672 bytes.
Global variables use 562 bytes (21%) of dynamic memory, leaving 1998 bytes for local variables. Maximum is 2560 bytes.`

**Comment by trsonic** [comment]
Hi,

it's just a warning. I haven't tracked it yet, but it does not stop the Arduino project from compiling and the HT works fine with it.

Best,
T.
