### ISSUE TITLE
IMU Calibration

### ISSUE THREAD

**Issue by jaredsking123** [trsonic/nvsonic-head-tracker#8]
Hi There,

Having an issue with IMU calibration - or more specifically getting corollary YAW values out of OSC Bridge as would be expected based on the real world (or gaze direction once attached to headphones) orientation of the IMU.

e.g. No matter the starting physical orientation of the IMU once Reset to all 0,0,0 I am unable to get 'YAW' to output 90° if I rotate the IMU 90°, -45° if rotating IMU -45°, etc. All code seems to have compiled correctly. 

Any guidance here?

**Comment by jaredsking123** [comment]
Hello, 

Would love to get some guidance on this please!

**Comment by trsonic** [comment]
Hi!

Could you post a picture of your headtracker attached? Currently, there is
only a single device orientation supported (look at the photo in readme for
reference).

Best,
T.
