### ISSUE TITLE
Help. It stoped transmitting to OSC Bridge

### ISSUE THREAD

**Issue by TanithCain** [trsonic/nvsonic-head-tracker#9]
Hi, when I first builded the headtracker it worked fine, now i reassembled it and everything looks right, the leds look like last time, the connection is there but i don't get any data in the OSC bridge when i rotate. I tried reuploading the script to the arduino, restarting the bridge, resoldering the pins, nothing helped

**Comment by trsonic** [comment]
Hi, could you check first if you get the data stream over serial? You can use the serial monitor from Arduino IDE.

**Comment by TanithCain** [comment]
Thanks for the fast reply, i totally forgot about this feature. I don't know much about programming but i think this doesn't look right.
![2020-11-16 (2)](https://user-images.githubusercontent.com/74546290/99260503-c0466900-281b-11eb-84f4-a4b2deef927e.png)

**Comment by trsonic** [comment]
Yeah, most likely something is wrong with the device. Maybe the MPU board is broken. Or there is a wiring problem.

Feel free to post some pictures of your assembled device and we can look at it together.

**Comment by TanithCain** [comment]
so this are pics of both parts front and back:

![IMG_20201116_153319](https://user-images.githubusercontent.com/74546290/99266097-b4aa7080-2822-11eb-8e65-fd68c56afd15.jpg)
![IMG_20201116_153335](https://user-images.githubusercontent.com/74546290/99266107-b7a56100-2822-11eb-8ec9-11b3fae2508a.jpg)
![IMG_20201116_153420](https://user-images.githubusercontent.com/74546290/99266110-b83df780-2822-11eb-986c-8d51a2bd65a0.jpg)
![IMG_20201116_153458](https://user-images.githubusercontent.com/74546290/99266368-f9360c00-2822-11eb-8c40-7821ba36faef.jpg)

**Comment by trsonic** [comment]
The IMU board looks like MPU-6050. It is not supported in this project. Look for MPU-9250 board.

The soldering work could be improved! Good luck!

**Comment by TanithCain** [comment]
Thank you so muchfor your help. I don#t know how i managed to get it to work before but i'll buy the right board and try it again.

**Comment by trsonic** [comment]
It could have worked by some chance, but certainly the tracking wasn't stable. Feel free to open this thread again if you encounter any more issues.
